name: Bug Report
description: Report a bug in a bug report so the bug is reported in a bug report
title: "(Bug): <title>"
labels: ["bug"]
assignees: HighSpeed85
body:
  - type: input
    id: ver
    attributes:
      label: Mod Version
      description: "What version of the mod is the bug happening on?"
      placeholder: "vYEAR.MONTH.DAY.IDK"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A detailed and clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "How to replicate"
      description: "How did this bug happen? Include detailed steps."
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What do you think is supposed to happen?
    validations:
      required: true
  - type: upload
    attributes:
      label: Upload relevant files
      description: "Add relevant screenshots, video or text files (most likely logs)."
    validations:
      required: false
      accept: ".zip,.gz,.pdf,.docx,.png,.jpg,.jpeg,.gif,.svg,.webp,.mp4,.mov,.webm,.json,.py,.js,.ts,.log,.txt,.csv"
